=== SU15-TeamAbsolut/Kundbolaget/Dokumentation/json/orderSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "JsonOrder",
  "additionalProperties": false,
  "required": [
    "CustomerId",
    "DeliveryDate",
    "DeliveryAddressId",
    "OrderRows"
  ],
  "properties": {
    "CustomerId": {
      "type": "integer"
    },
    "DeliveryDate": {
      "type": "string",
      "format": "date-time"
    },
    "DeliveryAddressId": {
      "type": "integer"
    },
    "OrderRows": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/JsonOrderRow"
      }
    }
  },
  "definitions": {
    "JsonOrderRow": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ArticleId",
        "Amount"
      ],
      "properties": {
        "ArticleId": {
          "type": "integer"
        },
        "Amount": {
          "type": "integer"
        }
      }
    }
  }
}

=== SU15-TeamAbsolut/Kundbolaget/JsonSampleFiles/order-Systembolaget.json
{
  "CustomerId":10002,
  "DeliveryDate":"2018-03-18T22:31:21.7282317+01:00",
  "DeliveryAddressId":28,
  "OrderRows":[
    {
      "ArticleId":10004,
      "Amount":28
    },
    {
      "ArticleId":10017,
      "Amount":8
    },
    {
      "ArticleId":10031,
      "Amount":150
    },
    {
      "ArticleId":10019,
      "Amount":30
    },
    {
      "ArticleId":10021,
      "Amount":19
    },
    {
      "ArticleId":10028,
      "Amount":60
    },
    {
      "ArticleId":10029,
      "Amount":180
    }
  ]
}
